project:
  type: website
  output-dir: docs

website:
  title: "IBT-HSG - Slides"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: slide_overview.qmd
    right: 
      - icon: github
        href: https://github.com/saboustocker/slides
        aria-label: GitHub

execute:
  echo: true

format:
  html:
    tempalte: sandstone