project:
  type: website
  output-dir: docs

website:
  title: "IBT-HSG - Slides"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: slides.qmd
    right: 
      - icon: github
        href: https://github.com/saboustocker/slides
        aria-label: GitHub

format: 
  html:
    theme: [darkly, styles.scss]
    

execute:
  echo: true