project:
  type: website
  output-dir: docs

website:
  title: "IBT-HSG - Slides"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
    right: 
      - icon: github
        href: https://github.com/saboustocker/slides
        aria-label: GitHub

format: 
  html:
    theme: darkly
    css: styles.scss
    

execute:
  echo: true